<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <SUITESPARSE_ROOT>$(PEABODY_DEPENDENCY_DIR)</SUITESPARSE_ROOT>
    <SUITESPARSE_DIR>$(SUITESPARSE_ROOT)</SUITESPARSE_DIR>
    <SUITESPARSE_INC_DIR>$(SUITESPARSE_ROOT)include\suitesparse\</SUITESPARSE_INC_DIR>
    <SUITESPARSE_LIB_DIR>$(SUITESPARSE_ROOT)lib\</SUITESPARSE_LIB_DIR>
    <SUITESPARSE_MKL_LIB_DIR>$(SUITESPARSE_ROOT)lib\</SUITESPARSE_MKL_LIB_DIR>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SUITESPARSE_INC_DIR);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SUITESPARSE_MKL_LIB_DIR);$(SUITESPARSE_LIB_DIR);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>amd.lib;btf.lib;camd.lib;ccolamd.lib;cholmod.lib;colamd.lib;cxsparse.lib;klu.lib;ldl.lib;suitesparseconfig.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>%(Command)</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="SUITESPARSE_ROOT">
      <Value>$(SUITESPARSE_ROOT)</Value>
    </BuildMacro>
    <BuildMacro Include="SUITESPARSE_DIR">
      <Value>$(SUITESPARSE_DIR)</Value>
    </BuildMacro>
    <BuildMacro Include="SUITESPARSE_INC_DIR">
      <Value>$(SUITESPARSE_INC_DIR)</Value>
    </BuildMacro>
    <BuildMacro Include="SUITESPARSE_LIB_DIR">
      <Value>$(SUITESPARSE_LIB_DIR)</Value>
    </BuildMacro>
    <BuildMacro Include="SUITESPARSE_MKL_LIB_DIR">
      <Value>$(SUITESPARSE_MKL_LIB_DIR)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
